name: Automated testing with unusual TeX Live configuration

# We only run when manually triggered
on:
  workflow_dispatch:
    inputs:
      fail-fast:
        default: false
        description: 'Fail run on first error'
        required: true
        type: boolean
      skip-docs:
        default: false
        description: 'Do not build documentation'
        required: true
        type: boolean
      texlive-version:
        default: 2026
        description: 'TeX Live version to test against'
        required: true
        type: number
      luatex-snapshot:
        default: false
        description: 'Test with snapshot version of LuaTeX'
        required: true
        type: boolean

jobs:
  # Update the TeX Live tree if necessary
  texlive-cache:
    runs-on: ubuntu-latest
    name: Update TeX Live
    outputs:
      cache_key: ${{ github.event_name == 'workflow_dispatch' && inputs.luatex-snapshot && format('workflow-{0}-{1}', github.run_id, github.run_attempt) || steps.texlive.outputs.cache_key }}
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install TeX Live
        id: texlive
        uses: zauguin/install-texlive@v4
        with:
          # List the required TeX Live packages in a separate file to allow reuse in
          # different workflows.
          package_file: .github/tl_packages
          texlive_version: ${{ github.event_name == 'workflow_dispatch' && inputs.texlive-version }}
      - name: Install snapshot LuaTeX binary
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.luatex-snapshot }}
        run: |
          curl -O https://build.contextgarden.net/dl/luatex/x86_64-linux/luahbtex
          chmod +x luahbtex
          mv luahbtex $(which luahbtex)
          fmtutil-sys --byengine luahbtex
      - name: Save TeX Live to cache
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.luatex-snapshot }}
        uses: actions/cache/save@v5
        id: cache
        with:
          path: ~/texlive
          key: workflow-${{ github.run_id }}-${{ github.run_attempt }}
  # The l3build job contains the actual work. We misuse the matrix mechanism to
  # create three jobs which only differ in minimal elements.
  # For tags we do not run this since we run the release job instead.
  l3build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.fail-fast) }}
      matrix:
        # include indicates that we want to set explicitly these combinations
        # and don't want full matrix testing.
        include:
          - module: base
            config: build
            engine: pdftex
          - module: base
            config: build
            engine: xetex
          - module: base
            config: build
            engine: luatex
            extra_command: kpsewhich -mktex=tfm -must-exist ecssdc10.tfm
            last: m3expl009
          - module: base
            config: build
            engine: luatex
            extra_command: kpsewhich -mktex=tfm -must-exist ecssdc10.tfm
            first: m3expl009
            last: tlb0001
          - module: base
            config: build
            engine: luatex
            extra_command: kpsewhich -mktex=tfm -must-exist ecssdc10.tfm
            first: tlb0001
            last: tlcs01a
          - module: base
            config: build
            engine: luatex
            extra_command: kpsewhich -mktex=tfm -must-exist ecssdc10.tfm
            first: tlcs01a
          - module: base
            config: config-1run
          - module: base
            config: config-TU
          - module: base
            config: config-doc
          - module: base
            config: config-legacy
          - module: base
            config: config-ltcmd
          - module: base
            config: config-lthooks
          - module: base
            config: config-lthooks2
          - module: base
            config: config-lttemplates
          - module: base
            config: config-ltmarks
          - module: required/amsmath
          - module: required/cyrillic
          - module: required/firstaid
          - module: required/graphics
          - module: required/latex-lab
            config: build
          - module: required/latex-lab
            config: config-OR
          - module: required/latex-lab
            config: config-math
          - module: required/latex-lab
            config: config-math-luatex
          - module: required/latex-lab
            config: config-OR-luatex
          - module: required/latex-lab
            config: config-sec
          - module: required/latex-lab
            config: config-toc
          - module: required/latex-lab
            config: config-block
            last: blocks-list-04
          - module: required/latex-lab
            config: config-block
            first: blocks-list-04
          - module: required/latex-lab
            config: config-graphic
          - module: required/latex-lab
            config: config-minipage
          - module: required/latex-lab
            config: config-float
          - module: required/latex-lab
            config: config-footnote
          - module: required/latex-lab
            config: config-bib
          - module: required/latex-lab
            config: config-LM-tagging
          - module: required/latex-lab
            config: config-table-pdftex
          - module: required/latex-lab
            config: config-table-luatex
          - module: required/latex-lab
            config: config-title
          - module: required/latex-lab
            config: config-firstaid
          - module: required/tools
    name: "Tests: ${{ matrix.module }}\
      ${{ matrix.config && format(' - {0}', matrix.config) || ''}}\
      ${{ matrix.engine && format(' - {0}', matrix.engine) || ''}}\
      ${{ (matrix.first || matrix.last) && format(' ({0} - {1})', matrix.first || '<first>', matrix.last || '<last>') || ''}}"
    needs: texlive-cache
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v6
      # We need Ghostscript for dvips and XeTeX tests.
      - run: sudo apt-get update && sudo apt-get install ghostscript
      - name: Restore TeX Live from cache
        uses: actions/cache/restore@v5
        with:
          path: ~/texlive
          key: ${{ needs.texlive-cache.outputs.cache_key }}
          fail-on-cache-miss: true
      - run: echo "$HOME/texlive/bin/x86_64-linux" >> "$GITHUB_PATH"
      - if: ${{ matrix.extra_command }}
        run: ${{ matrix.extra_command }}
      - name: Run l3build
        working-directory: ${{ matrix.module }}
        run: "l3build check
          ${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.fail-fast)) && '-H' || '-S' }}
          -q --show-log-on-error
          ${{ matrix.config && format('-c {0}', matrix.config) || ''}}
          ${{ matrix.engine && format('-e {0}', matrix.engine) || ''}}
          ${{ matrix.first && format('--first {0}', matrix.first) || ''}}
          ${{ matrix.last && format('--last {0}', matrix.last) || ''}}"
      # "/" is one of invalid characters in artifact names
      # see https://github.com/actions/toolkit/blob/ef77c9d60bdb03700d7758b0d04b88446e72a896/packages/artifact/src/internal/upload/path-and-artifact-name-validation.ts
      - name: Sanitize artifact name
        if: ${{ always() }}
        run: |
          name="testfiles-${{ matrix.module }}${{ matrix.config && format('-{0}', matrix.config)  || ''}}${{ matrix.engine && format('-{0}', matrix.engine) || ''}}"
          # replace all "/" with "_"
          echo "artifact_name=${name//\//_}" >> "$GITHUB_ENV"
      # Now we create the artifacts for the logs of failed tests
      - name: Archive failed test output
        if: ${{ always() }}
        uses: zauguin/l3build-failure-artifacts@v1
        with:
          # example names:
          # - "testfiles-base-build-pdflatex"
          # - "testfiles-base-config-1run"
          # - "testfiles-required_amsmath"
          name: ${{ env.artifact_name }}
          # Decide how long to keep the test output artifact:
          retention-days: 3
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.fail-fast) }}
      matrix:
        include:
          - module: base
            component: 1
          - module: base
            component: 2
          - module: base
            component: 3
          - module: required/amsmath
          - module: required/cyrillic
          - module: required/firstaid
          - module: required/graphics
          - module: required/latex-lab
            component: 1
          - module: required/latex-lab
            component: 2
          - module: required/latex-lab
            component: 3
          - module: required/tools
    name: "Documentation: ${{ matrix.module }}\
      ${{ matrix.component && format(' ({0})', matrix.component) || ''}}"
    needs: texlive-cache
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v6
      # We need Ghostscript for dvips and XeTeX tests.
      - run: sudo apt-get update && sudo apt-get install ghostscript
      - name: Restore TeX Live from cache
        uses: actions/cache/restore@v5
        with:
          path: ~/texlive
          key: ${{ needs.texlive-cache.outputs.cache_key }}
          fail-on-cache-miss: true
      - run: echo "$HOME/texlive/bin/x86_64-linux" >> "$GITHUB_PATH"
      # LTX_DOC_COMPONENT is used by some of the build.lua files
      - if: ${{ matrix.component }}
        run: echo "LTX_DOC_COMPONENT=${{ matrix.component }}" >> "$GITHUB_ENV"
      - name: Run l3build
        working-directory: ${{ matrix.module }}
        run: "l3build doc -q
          ${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.fail-fast)) && '-H ' || '' }}
          --show-log-on-error"
      # Now we create the artifacts for the generated documentation
      - name: Sanitize artifact name
        shell: bash
        run: |
          name="Documentation-${{ matrix.module }}${{ matrix.component && format('-{0}', matrix.component) || ''}}"
          # replace all "/" with "_"
          echo "artifact_name=${name//\//_}" >> "$GITHUB_ENV"
      - name: Archive documentation
        uses: actions/upload-artifact@v7
        with:
          # example names: "Documentation-base-1", "Documentation-required"
          name: ${{ env.artifact_name }}
          path: |
            **/*.pdf
            !build
            !texmf
            !**/testfiles*
          # Decide how long to keep the test output artifact:
          retention-days: 21
